image: ubuntu:20.04 # Используем официальный образ.

stages:
  - test  # Определяем этап пайплайна.

test-nginx:
  stage: test  # Указываем, что job относится к этапу "test".
  script:
    - apt update && apt install -y nginx # Устанавливаем nginx.
    - which nginx    # Проверяем, установлен ли nginx (выводит путь к файлу).
    - nginx -v       # Показываем версию nginx.
    # Или более симпатичный вариант "which nginx && nginx -v".
    # Пайплайн написан при условии, что nginx установлен.
